from functools import wraps
from flask import Blueprint, render_template, request, redirect, url_for, session, current_app, jsonify

from app import limiter
from app.services import event_service, ticket_service
from app.utils.sanitize import clean, valid_uuid, valid_int, valid_float
from app.utils.csrf import csrf_protect

admin_bp = Blueprint("admin", __name__)

VALID_CURRENCIES = {"eur", "usd", "gbp"}


def admin_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not session.get("admin_authenticated"):
            return redirect(url_for("admin.login"))
        return f(*args, **kwargs)
    return decorated


def _parse_ticket_types(form, existing_event=None):
    """Parse ticket types from form data.

    Form fields: type_name[], type_price[], type_max_tickets[], type_id[],
                 access_codes_enabled[], access_codes_reusable[], access_codes_list[]
    """
    names = form.getlist("type_name[]")
    prices = form.getlist("type_price[]")
    max_tickets_list = form.getlist("type_max_tickets[]")
    type_ids = form.getlist("type_id[]")
    ac_enabled_list = form.getlist("access_codes_enabled[]")
    ac_reusable_list = form.getlist("access_codes_reusable[]")
    ac_codes_list = form.getlist("access_codes_list[]")

    # Build lookup for existing sold/reserved counters and access codes
    existing = {}
    if existing_event:
        for tt in existing_event.get("ticket_types", []):
            existing[tt["type_id"]] = tt

    ticket_types = []
    for i in range(len(names)):
        name = clean(names[i], max_length=100)
        price = valid_float(prices[i] if i < len(prices) else 0, min_val=0.0)
        max_t = valid_int(max_tickets_list[i] if i < len(max_tickets_list) else 1, min_val=1, max_val=100000, default=1)
        type_id = type_ids[i].strip() if i < len(type_ids) and type_ids[i].strip() else ""

        if not name:
            continue

        # Preserve sold/reserved from existing type
        prev = existing.get(type_id, {})

        entry = {
            "type_id": type_id or None,  # None = new, will be generated by model
            "name": name,
            "price": price,
            "max_tickets": max_t,
            "tickets_sold": prev.get("tickets_sold", 0),
            "tickets_reserved": prev.get("tickets_reserved", 0),
        }

        # Access codes
        ac_enabled = (ac_enabled_list[i] if i < len(ac_enabled_list) else "0") == "1"
        ac_reusable = (ac_reusable_list[i] if i < len(ac_reusable_list) else "0") == "1"
        ac_raw = ac_codes_list[i] if i < len(ac_codes_list) else ""

        if ac_enabled:
            # Parse, sanitize, and normalize codes to uppercase
            raw_codes = [clean(c, max_length=100).strip().upper() for c in ac_raw.split("\n")]
            raw_codes = [c for c in raw_codes if c]  # Remove empty
            raw_codes = list(dict.fromkeys(raw_codes))  # Remove duplicates, preserve order

            if ac_reusable:
                access_codes = [{"code": raw_codes[0], "used": False}] if raw_codes else []
            else:
                # Preserve used codes from existing data
                used_codes = [ac for ac in prev.get("access_codes", []) if ac.get("used")]
                used_code_set = {ac["code"] for ac in used_codes}
                new_codes = [{"code": c, "used": False} for c in raw_codes if c not in used_code_set]
                access_codes = used_codes + new_codes

            entry["access_codes_enabled"] = True
            entry["access_codes_reusable"] = ac_reusable
            entry["access_codes"] = access_codes
        else:
            entry["access_codes_enabled"] = False
            entry["access_codes_reusable"] = False
            entry["access_codes"] = []

        ticket_types.append(entry)

    return ticket_types


@admin_bp.route("/admin/login", methods=["GET", "POST"])
@limiter.limit("5 per minute", methods=["POST"])
@csrf_protect
def login():
    if request.method == "POST":
        password = request.form.get("password", "")
        if password == current_app.config["ADMIN_PASSWORD"]:
            session.permanent = True
            session["admin_authenticated"] = True
            return redirect(url_for("admin.dashboard"))
        return render_template("admin/login.html", error="Contrasena incorrecta")
    return render_template("admin/login.html")


@admin_bp.route("/admin/logout")
def logout():
    session.pop("admin_authenticated", None)
    return redirect(url_for("main.index"))


@admin_bp.route("/admin")
@admin_required
def dashboard():
    events = event_service.get_all_events()
    return render_template("admin/dashboard.html", events=events)


@admin_bp.route("/admin/event/new")
@admin_required
def new_event():
    return render_template("admin/event_form.html", event=None)


@admin_bp.route("/admin/event/create", methods=["POST"])
@admin_required
@csrf_protect
def create_event():
    currency = clean(request.form.get("currency", "eur"), max_length=3).lower()
    if currency not in VALID_CURRENCIES:
        currency = "eur"

    ticket_types = _parse_ticket_types(request.form)
    if not ticket_types:
        return render_template("admin/event_form.html", event=None,
                               error="Anade al menos un tipo de entrada"), 400

    data = {
        "name": clean(request.form.get("name", ""), max_length=200),
        "description": clean(request.form.get("description", ""), max_length=2000),
        "date": clean(request.form.get("date", ""), max_length=30),
        "venue": clean(request.form.get("venue", ""), max_length=200),
        "currency": currency,
        "ticket_types": ticket_types,
    }

    if not data["name"] or not data["date"] or not data["venue"]:
        return render_template("admin/event_form.html", event=None, error="Faltan campos obligatorios"), 400

    image = request.files.get("image")
    if image and image.filename:
        try:
            data["image_filename"] = event_service.save_image(image)
        except ValueError as e:
            return render_template("admin/event_form.html", event=None, error=str(e))

    event_service.create_event(data)
    return redirect(url_for("admin.dashboard"))


@admin_bp.route("/admin/event/<event_id>")
@admin_required
def event_detail(event_id):
    event_id = valid_uuid(event_id)
    if not event_id:
        return "Evento no encontrado", 404
    event = event_service.get_event(event_id)
    if not event:
        return "Evento no encontrado", 404
    stats = ticket_service.get_event_stats(event_id)
    available = event_service.get_total_available(event)
    total_capacity = event_service.get_total_capacity(event)
    total_sold = event_service.get_total_sold(event)
    recent = ticket_service.get_recent_purchases(event_id)
    return render_template(
        "admin/event_detail.html",
        event=event,
        stats=stats,
        available=available,
        total_capacity=total_capacity,
        total_sold=total_sold,
        recent=recent,
    )


@admin_bp.route("/admin/event/<event_id>/edit")
@admin_required
def edit_event(event_id):
    event_id = valid_uuid(event_id)
    if not event_id:
        return "Evento no encontrado", 404
    event = event_service.get_event(event_id)
    if not event:
        return "Evento no encontrado", 404
    return render_template("admin/event_form.html", event=event)


@admin_bp.route("/admin/event/<event_id>/update", methods=["POST"])
@admin_required
@csrf_protect
def update_event(event_id):
    event_id = valid_uuid(event_id)
    if not event_id:
        return "Evento no encontrado", 404

    existing_event = event_service.get_event(event_id)
    if not existing_event:
        return "Evento no encontrado", 404

    currency = clean(request.form.get("currency", "eur"), max_length=3).lower()
    if currency not in VALID_CURRENCIES:
        currency = "eur"

    ticket_types = _parse_ticket_types(request.form, existing_event)
    if not ticket_types:
        return render_template("admin/event_form.html", event=existing_event,
                               error="Anade al menos un tipo de entrada"), 400

    data = {
        "name": clean(request.form.get("name", ""), max_length=200),
        "description": clean(request.form.get("description", ""), max_length=2000),
        "date": clean(request.form.get("date", ""), max_length=30),
        "venue": clean(request.form.get("venue", ""), max_length=200),
        "currency": currency,
        "ticket_types": ticket_types,
    }

    image = request.files.get("image")
    if image and image.filename:
        try:
            data["image_filename"] = event_service.save_image(image)
        except ValueError as e:
            return render_template("admin/event_form.html", event=existing_event, error=str(e))
        if existing_event.get("image_filename"):
            event_service.delete_image(existing_event["image_filename"])

    event_service.update_event(event_id, data)
    return redirect(url_for("admin.event_detail", event_id=event_id))


@admin_bp.route("/admin/import-codes", methods=["POST"])
@admin_required
def import_codes():
    """Parse an Excel file (.xlsx) and return the codes as JSON."""
    file = request.files.get("file")
    if not file or not file.filename:
        return jsonify({"error": "No se ha enviado ningun archivo"}), 400

    filename = file.filename.lower()
    if not filename.endswith((".xlsx", ".xls")):
        return jsonify({"error": "Formato no soportado. Usa un archivo Excel (.xlsx)"}), 400

    try:
        import openpyxl
        wb = openpyxl.load_workbook(file, read_only=True, data_only=True)
        ws = wb.active
        codes = []
        for row in ws.iter_rows(min_col=1, max_col=1, values_only=True):
            val = row[0]
            if val is not None:
                code = str(val).strip().upper()
                if code:
                    codes.append(code)
        wb.close()
    except Exception:
        return jsonify({"error": "Error al leer el archivo Excel"}), 400

    # Deduplicate preserving order
    seen = set()
    unique_codes = []
    for c in codes:
        if c not in seen:
            seen.add(c)
            unique_codes.append(c)

    return jsonify({"codes": unique_codes}), 200


@admin_bp.route("/admin/event/<event_id>/status", methods=["POST"])
@admin_required
@csrf_protect
def change_status(event_id):
    event_id = valid_uuid(event_id)
    if not event_id:
        return "Evento no encontrado", 404
    new_status = request.form.get("status")
    event_service.change_status(event_id, new_status)
    return redirect(url_for("admin.dashboard"))
